apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-sse-dev

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: spring-sse-example
    newName: jeffbeard/spring-sse-example